version: '3'

volumes:
  database-volume: {}

services:
  django:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:12
    volumes:
      - database-volume:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"
    command: postgres -c 'statement_timeout=20000'
