# Generated by Django 4.2.7 on 2023-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Middle name'),
        ),
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
