# Generated by Django 4.2.7 on 2023-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(help_text='Имя компьютера', max_length=256, verbose_name='Имя ПК')),
                ('username', models.CharField(help_text='Имя пользователя', max_length=256, verbose_name='Пользователь')),
                ('device_display_name', models.CharField(help_text='Отображаемое имя устройства', max_length=512, verbose_name='Отображаемое имя устройства')),
                ('device_system_name', models.CharField(help_text='Системное имя устройства', max_length=256, verbose_name='Системное имя устройства')),
                ('device_serial_id', models.CharField(help_text='Серийный номер устройства', max_length=256, verbose_name='Серийный №')),
                ('soi_id', models.CharField(help_text='Номер заявки СОУ', max_length=256, verbose_name='№ заявки соу')),
                ('sadd_id', models.CharField(help_text='Номер заявки САДД', max_length=256, verbose_name='№ заявки САДД')),
                ('status', models.CharField(choices=[('prohibited', 'prohibited'), ('in_progress', 'In progress'), ('correct', 'Correct')], default='correct', help_text='Статус контроля доступа', max_length=12, verbose_name='Статус')),
                ('comment', models.TextField(help_text='Комментарий к заявке', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Контроль доступа',
            },
        ),
    ]
