# Generated by Django 4.2.7 on 2023-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к заявке', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='device_serial_id',
            field=models.CharField(blank=True, help_text='Серийный номер устройства', max_length=256, verbose_name='Серийный №'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='sadd_id',
            field=models.CharField(blank=True, help_text='Номер заявки САДД', max_length=256, verbose_name='№ заявки САДД'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='soi_id',
            field=models.CharField(blank=True, help_text='Номер заявки СОУ', max_length=256, verbose_name='№ заявки соу'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='username',
            field=models.CharField(blank=True, help_text='Имя пользователя', max_length=256, verbose_name='Пользователь'),
        ),
    ]
