# Generated by Django 4.2.7 on 2023-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_accesscontrol_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='soi_id',
            field=models.CharField(blank=True, help_text='Номер заявки СОУ', max_length=256, verbose_name='№ заявки СОУ'),
        ),
    ]
